const {test,after}=require('node:test');
const assert=require('node:assert/strict');
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';
process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';
const admin=require('../functions/node_modules/firebase-admin');
admin.initializeApp({projectId:'demo-account-export'});
const {collectAccountData}=require('../functions/src/accountExport');
const db=admin.firestore();
after(()=>admin.app().delete());
test('export pages own content, preserves private boundaries and excludes credentials',async()=>{
 const uid='export-alice';await admin.auth().createUser({uid,email:'export@example.test',password:'synthetic-only-password'});
 await db.doc('profiles/legacy-export').set({uid,displayName:'Alice',password:'old-profile-password',refreshToken:'old-profile-token'});
 await db.doc('accountPrivate/'+uid).set({email:'export@example.test',password:'legacy-secret',pin:'1234',token:'secret'});
 const batch=db.batch();for(let i=0;i<105;i++)batch.set(db.doc('posts/export-'+String(i).padStart(3,'0')),{authorId:uid,text:'Own post '+i,createdAt:admin.firestore.Timestamp.now()});await batch.commit();
 await db.doc('posts/other').set({authorId:'other',text:'not mine'});
 await db.doc('posts/other/comments/own').set({authorId:uid,text:'my reply'});
 await db.doc('posts/other/reactions/'+uid).set({yeah:true});
 await db.doc('polls/other').set({authorId:'other'});await db.doc('polls/other/votes/'+uid).set({choice:1});
 await db.doc('conversations/thread').set({participants:[uid,'other']});
 await db.doc('conversations/thread/messages/own').set({senderId:uid,text:'own private message'});
 await db.doc('conversations/thread/messages/other').set({senderId:'other',text:'other private message'});
 await db.doc('reports/own').set({reporter:uid,reason:'private report'});
 await db.doc('reports/other').set({reporter:'other',reason:'other private report'});
 await db.doc('moderationDecisions/own').set({recipients:[uid],reason:'decision'});
 await db.doc('moderationDecisions/other').set({recipients:['other'],reason:'private other decision'});
 const result=await collectAccountData(uid),json=JSON.stringify(result),paths=result.records.map(row=>row.path);
 assert.equal(paths.filter(path=>/^posts\/export-\d+$/.test(path)).length,105);
 for(const path of ['profiles/legacy-export','posts/other/comments/own','posts/other/reactions/'+uid,'polls/other/votes/'+uid,'conversations/thread/messages/own','reports/own','moderationDecisions/own'])assert.ok(paths.includes(path),path);
 for(const path of ['posts/other','conversations/thread/messages/other','reports/other','moderationDecisions/other'])assert.ok(!paths.includes(path),path);
 for(const secret of ['old-profile-password','old-profile-token','synthetic-only-password','legacy-secret','1234','other private message','other private report','private other decision'])assert.ok(!json.includes(secret),secret);
 assert.equal(result.privateContact.email,'export@example.test');
 await assert.rejects(collectAccountData(uid,{maxBytes:100}),{code:'export-too-large'});
 await assert.rejects(collectAccountData(uid,{maxScanned:2}),{code:'export-too-large'});
});
