const {test,after}=require('node:test');
const assert=require('node:assert/strict');
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';
process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';
process.env.FIREBASE_STORAGE_EMULATOR_HOST='127.0.0.1:9199';
const admin=require('../functions/node_modules/firebase-admin');
admin.initializeApp({projectId:'demo-social-lifecycle',storageBucket:'demo-social-lifecycle.appspot.com'});
const {cleanPost,cleanAccount}=require('../functions/src/socialCleanup');
const db=admin.firestore();
after(()=>admin.app().delete());
test('post cleanup removes descendants, related feed records and only its own media',async()=>{
 const bucket=admin.storage().bucket();
 await bucket.file('media/cleanup-owner/post').save('image'); await bucket.file('media/other/keep').save('keep');
 await db.doc('posts/cleanup').set({authorId:'cleanup-owner',media:{path:'media/cleanup-owner/post'}});
 await db.doc('posts/cleanup/comments/c').set({authorId:'other',text:'reply'});
 await db.doc('posts/cleanup/reactions/other').set({yeah:true});
 await db.doc('reposts/r').set({postId:'cleanup'});await db.doc('users/other/notifications/n').set({postId:'cleanup'});
 await db.doc('reports/r').set({postId:'cleanup'}); await db.doc('posts/keep').set({authorId:'other'});
 await cleanPost('cleanup',(await db.doc('posts/cleanup').get()).data());
 for(const path of ['posts/cleanup/comments','posts/cleanup/reactions','reposts','reports','users/other/notifications'])assert.equal((await db.collection(path).get()).size,0);
 assert.equal((await bucket.file('media/cleanup-owner/post').exists())[0],false);
 assert.equal((await bucket.file('media/other/keep').exists())[0],true);
 assert.equal((await db.doc('posts/keep').get()).exists,true);
 await cleanPost('cleanup',{authorId:'cleanup-owner',media:{path:'media/other/keep'}});
 assert.equal((await bucket.file('media/other/keep').exists())[0],true);
});
test('account cleanup is repeatable, erases legacy identity and own content while retaining other people content',async()=>{
 const uid='delete-me';await admin.auth().createUser({uid,email:'delete-me@example.test'});
 await db.doc('profiles/12345').set({uid,displayName:'Legacy'});await db.doc('profiles/keep').set({uid:'other'});
 await db.doc('posts/own').set({authorId:uid});await db.doc('posts/keep/comments/own').set({authorId:uid});
 await db.doc('posts/keep/reactions/'+uid).set({yeah:true});
 await db.doc('polls/own').set({authorId:uid});await db.doc('polls/own/votes/other').set({choice:0});
 await db.doc('polls/keep').set({authorId:'other'});await db.doc('polls/keep/votes/'+uid).set({choice:0});
 await db.doc('conversations/thread').set({participants:[uid,'other']});
 await db.doc('conversations/thread/messages/own').set({senderId:uid});await db.doc('conversations/thread/messages/keep').set({senderId:'other',text:'Keep'});
 await db.doc('friendships/f').set({participants:[uid,'other']});await db.doc('boards/keep').set({ownerId:uid,name:'Public club'});
 await db.doc('users/'+uid+'/blocks/other').set({});await db.doc('accountPrivate/'+uid).set({email:'private@example.test'});
 await admin.storage().bucket().file('media/'+uid+'/orphan').save('unused image');
 await cleanAccount(uid);await cleanAccount(uid);
 for(const path of ['profiles/12345','posts/own','posts/keep/comments/own','posts/keep/reactions/'+uid,'polls/own','polls/own/votes/other','polls/keep/votes/'+uid,'conversations/thread/messages/own','friendships/f','accountPrivate/'+uid,'users/'+uid+'/blocks/other'])assert.equal((await db.doc(path).get()).exists,false,path);
 for(const path of ['profiles/keep','posts/keep','polls/keep','conversations/thread/messages/keep','boards/keep'])assert.equal((await db.doc(path).get()).exists,true,path);
 assert.equal((await db.doc('boards/keep').get()).data().ownerId,null);
 assert.equal((await db.doc('accountDeletions/'+uid).get()).data().status,'complete');
 assert.equal((await admin.storage().bucket().file('media/'+uid+'/orphan').exists())[0],false);
 await assert.rejects(admin.auth().getUser(uid),{code:'auth/user-not-found'});
});

test('shared media is retained until its last public reference is removed',async()=>{
 const bucket=admin.storage().bucket(),media={path:'media/shared-owner/shared'};
 await bucket.file(media.path).save('shared image');
 await db.doc('posts/shared-one').set({authorId:'shared-owner',media});await db.doc('posts/shared-two').set({authorId:'shared-owner',media});
 await cleanPost('shared-one',{authorId:'shared-owner',media});assert.equal((await bucket.file(media.path).exists())[0],true);
 await db.doc('posts/shared-one').delete();
 await db.doc('profiles/shared-owner').set({uid:'shared-owner',avatarPath:media.path});
 await cleanPost('shared-two',{authorId:'shared-owner',media});assert.equal((await bucket.file(media.path).exists())[0],true);
 await db.doc('profiles/shared-owner').delete();
 await cleanPost('shared-two',{authorId:'shared-owner',media});assert.equal((await bucket.file(media.path).exists())[0],false);
});
